### ISSUE TITLE
Run commands defined under build, run and test

### ISSUE THREAD

**Issue by joaorafaelm** [joaorafaelm/py-compose#1]
Execute commands listed in `build`, `run` and `test` stages.
 ```yaml
services:
    app:
        basedir: ./
        environment:
            DEBUG: True
        build:
            - pipenv install -r requirements.txt --python 3.6.3
        run:
            - python manage.py runserver
        depends_on:
            - otoapp
        test:
            - py.test

    otoapp:
        basedir: ./
```
