### ISSUE TITLE
Clone git repo defined as basedir

### ISSUE THREAD

**Issue by joaorafaelm** [joaorafaelm/py-compose#2]
Clone repo if a git URI is defined as base dir.
```yaml
services:
    app:
        basedir: git@github.com:joaorafaelm/py-compose.git
```
